services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1 #You change the name to be whatever you want
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_USER=cassandra #don't change this
      - CASSANDRA_PASSWORD=cassandra_password #change this to whatever you want to use
      - CASSANDRA_PASSWORD_SEEDER=true  # Only needed for the seed node
    networks:
      - cassandra-network

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2 #You change the name to be whatever you want
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=100M
    networks:
      - cassandra-network

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3 #You change the name to be whatever you want
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=100M
    networks:
      - cassandra-network

networks:
  cassandra-network:
    driver: bridge
