services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3, cassandra4
      - CASSANDRA_NUM_TOKENS=128
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_USER=cassandra #don't change this
      - CASSANDRA_PASSWORD=casspass #change this to whatever you want to use
      - CASSANDRA_PASSWORD_SEEDER=true  # Only needed for the seed node
    volumes:
      - ./cassandra1_data:/var/lib/cassandra
    networks:
      - cassandra-network

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3, cassandra4
      - CASSANDRA_NUM_TOKENS=128
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - ./cassandra2_data:/var/lib/cassandra
    networks:
      - cassandra-network

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3, cassandra4
      - CASSANDRA_NUM_TOKENS=128
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - ./cassandra3_data:/var/lib/cassandra
    networks:
      - cassandra-network

  cassandra4:
    image: cassandra:latest
    container_name: cassandra4
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3, cassandra4
      - CASSANDRA_NUM_TOKENS=128
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - ./cassandra4_data:/var/lib/cassandra
    networks:
      - cassandra-network

volumes:
  cassandra1_data:
  cassandra2_data:
  cassandra3_data:
  cassandra4_data:


networks:
  cassandra-network:
    driver: bridge
